@startuml

skinparam componentStyle uml2

[Client] - RESTinterface
RESTinterface - [Server]

[Server] - DatabaseAccess
DatabaseAccess - [CRUD\nDatabase]

package "External APIs"{
    [Quote API] - Server
    [Map API] - Server
}



@enduml