@startuml

skinparam componentStyle uml2

[User] -down- UI
UI - [Client]
[Client] - REST
REST - [Server]

[Server] -down- DatabaseAccess

database "Database" {
DatabaseAccess -down- [CRUD\nDatabase]
}

package "External APIs"{
    [Quote API] -- Server
    [Map API] -- Server
}

@enduml