@startuml

(*)  -> [<b>Rob begins\n<b>his turn] "dice are rolled"
if dice score? then
    -left-> [{2...12} \ 7] "resources of the tiles\nwith that score are
                        distributed to the\nplayers nearby" as diceAll
    else

    -right-> [7] players count their\nresource cards
    -right-> if "if cards are..."
        --> [>7] return half of the\ncards to the bank\n (rounded down)
        --> "Rob moves\nthe thief on a\nnew tile" as moveThief
        else
        --> [<=7] do nothing
        --> moveThief
    endif

    -right-> if are there villages\non the new tile?
        --> [yes] Rob can steal a card\nfrom one of the\nvillages' owner
        --> action
        else
        --> [no] action


endif

diceAll --> "An action popup\nis shown to Rob" as action
action --> [Rob can\nact now] "Rob chooses an action"

if action? then
    --> build\nsomething
    if "what to build?"
        --> [village] Rob sets his\nnew village
        --> action
        else
        --> [road] Rob sets his\nnew road
        --> action
        else
        --> [city] Rob sets his\nnew city
        --> action
    endif

    else
    --> trade
    if "with whom?"
        --> [with bank] Rob trades freely\n(4:1, 3:1 or 2:1)
/'        if "has port?"
            --> [no] "4:1 trading"
            --> action
            else
            --> [normal\nport] "3:1 trading"
            --> action
            else
            --> [specific\nport] "2:1 trading"
            --> action
        endif'/
        --> action

        else
        ..> [<i>(opt) with\n<i>players] "<i>(opt) Rob asks others
                                   <i>if they want to trade"
        ..> action
    endif

    else
    --> buy development\ncard
    --> action
    else
    --> use development card
    --> action
    else
    -right-> "pass turn"
    --> [turn is passed\nto next player] (*)
@enduml