@startuml
(*)  --> "display login page"
If "Is the user registered?" then
--> [Yes] "user fills in credentials and clicks on login"
If "Are credentials correct?"
--> [Yes] "login to game menu"
-->(*)
else
--> [No] "display error message"
--> "display login page"
Endif

else
--> [No] "user clicks on sign up button"
--> "registration page is shown"
--> "user inputs credentials and clicks on sign up button"
--> "display login page"
Endif
@enduml