@startuml
(*)  --> "game starts, board is shown"
--> "dices are rolled for every player"
--> "player with highest nr sets his first village"
If "input is verbose" then
--> [Yes] "turn on verbosity"
--> "run command"
else
--> "run command"
Endif
-->(*)
@enduml